#!/bin/bash

echo "🚀 RedditLeads Quick Setup Script"
echo "=============================="

echo ""
echo "✅ Dependencies installed"
echo "✅ Database created and configured"
echo "✅ Environment files created"
echo ""

echo "📋 NEXT STEPS - You need to configure these services:"
echo ""

echo "1. 🔴 REDDIT API SETUP:"
echo "   - Go to: https://www.reddit.com/prefs/apps"
echo "   - Click 'Create App' or 'Create Another App'"
echo "   - Choose 'script' as app type"
echo "   - Update these in .env:"
echo "     REDDIT_CLIENT_ID='your_client_id'"
echo "     REDDIT_CLIENT_SECRET='your_client_secret'"
echo "     REDDIT_USER_AGENT='RedditLeads/1.0 by your_username'"
echo ""

echo "2. 🔐 CLERK AUTHENTICATION:"
echo "   - Go to: https://clerk.com"
echo "   - Create new application"
echo "   - Update these in .env and frontend/.env.local:"
echo "     CLERK_PUBLISHABLE_KEY='pk_test_...'"
echo "     CLERK_SECRET_KEY='sk_test_...'"
echo ""

echo "3. 🤖 AI SERVICES:"
echo "   - OpenAI: https://platform.openai.com/api-keys"
echo "   - Google AI: https://makersuite.google.com/app/apikey"
echo "   - Perplexity: https://www.perplexity.ai/settings/api"
echo "   - Update OPENAI_API_KEY, GOOGLE_GENERATIVE_AI_API_KEY, PERPLEXITY_API_KEY in .env"
echo ""

echo "4. 📧 EMAIL SERVICE:"
echo "   - Go to: https://resend.com"
echo "   - Create account and get API key"
echo "   - Update RESEND_API_KEY in .env"
echo ""

echo "5. 🔄 REDDIT REFRESH TOKEN:"
echo "   - Run: node generate-token.js"
echo "   - Follow the instructions to get refresh token"
echo "   - Update REDDIT_REFRESH_TOKEN in .env"
echo ""

echo "🎯 TO START THE APPLICATION:"
echo ""
echo "Terminal 1 (Backend):"
echo "  npm run dev"
echo ""
echo "Terminal 2 (Frontend):"
echo "  cd frontend && npm run dev"
echo ""
echo "Terminal 3 (Lead Generator - Optional):"
echo "  cd lead-generator && python main.py"
echo ""
echo "🌐 Then visit: http://localhost:3000"
echo ""
echo "📖 Full setup guide: SETUP_GUIDE.md"
